# Nom de l'application
spring.application.name=${sp.app.name}

# Configuration de la source de donnees
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver}
spring.datasource.type=${db.type}

# Configuration du pool de connexions Hikari
spring.datasource.hikari.pool-name=${db.hikari.pool.name}
spring.datasource.hikari.maximum-pool-size=10

# Configuration JPA
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql

# Configuration du serveur
#server.port=9090

#debug=true